name: Amazon S3 Sample

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name : Init yarn
        run: |
          yarn init -y
          
      - name : Install dependency
        run: |
          yarn config set -H enableImmutableInstalls false
          yarn
          cat ./package.json

      - name: Build
        run: yarn workspaces foreach -A run publish

      - name : Replace name
        run: |
          before="/export/slide"
          after="/slide
          find index.html | xargs sed -i 's/$before/$after/g'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload file to S3
        env:
          S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET }}
        run: |
          ls /export
          aws s3 cp /export s3://$S3_UPLOAD_BUCKET --recursive
